<!doctype html>
<html lang="it">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Feedback - ACTV Live</title><?php require COMMON_HTML_HEAD; ?><link rel="stylesheet" href="/css/admin.css"><link rel="stylesheet" href="/css/admin-shell.css"></head>
<body class="admin-page">
<main class="admin-container">
    <div class="admin-header"><div><h1>Feedback utenti</h1><p class="text-muted mb-0">Segnalazioni e proposte ricevute da ACTV Live.</p></div><div class="d-flex gap-2"><a href="/admin/dashboard" class="btn btn-sm btn-outline-primary">Dashboard</a><a href="/admin/logout" class="btn btn-sm btn-outline-warning">Logout</a></div></div>
    <form class="feedback-filters" method="get"><select name="category"><option value="">Tutte le categorie</option><?php foreach (['feature'=>'Funzionalità','bug'=>'Bug','improvement'=>'Miglioramento','question'=>'Domanda','other'=>'Altro'] as $value=>$label): ?><option value="<?= $value ?>" <?= $category === $value ? 'selected' : '' ?>><?= $label ?></option><?php endforeach; ?></select><select name="status"><option value="">Tutti gli stati</option><?php foreach (['new'=>'Nuovo','in_progress'=>'In lavorazione','resolved'=>'Risolto','archived'=>'Archiviato'] as $value=>$label): ?><option value="<?= $value ?>" <?= $status === $value ? 'selected' : '' ?>><?= $label ?></option><?php endforeach; ?></select><button class="btn btn-primary" type="submit">Filtra</button></form>
    <?php if (empty($feedback)): ?><div class="panel-card"><p class="mb-0">Nessun feedback trovato.</p></div><?php else: ?>
    <div class="panel-card table-responsive"><table class="admin-table"><thead><tr><th>Data</th><th>Categoria</th><th>Priorità</th><th>Stato</th><th>Feedback</th><th>Contatto</th></tr></thead><tbody>
    <?php foreach ($feedback as $item): ?><tr><td class="feedback-date"><?= htmlspecialchars((string)$item['created_at']) ?></td><td><span class="feedback-tag tag-<?= htmlspecialchars($item['category']) ?>"><?= htmlspecialchars($item['category']) ?></span></td><td><?= htmlspecialchars($item['priority']) ?></td><td><?= htmlspecialchars($item['status']) ?></td><td><strong><?= htmlspecialchars($item['subject'] ?: 'Senza titolo') ?></strong><div class="feedback-message"><?= nl2br(htmlspecialchars($item['message'])) ?></div></td><td><?= htmlspecialchars($item['name'] ?: 'Anonimo') ?><?php if ($item['email']): ?><br><a href="mailto:<?= htmlspecialchars($item['email']) ?>"><?= htmlspecialchars($item['email']) ?></a><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
</main></body></html>
