<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Trova Percorso - ACTV</title>
    <?php require COMMON_HTML_HEAD; ?>
    <link rel="stylesheet" href="/css/routeFinder.css">
</head>
<body>

    <!-- Header -->
    <div class="header-green">
        <div style="height: 20px;">
            <a href="/" style="color: white; text-decoration: none; font-size: 24px;">&larr;</a>
        </div>
        <div class="header-title">Trova<br>Percorso</div>
    </div>

    <!-- Main Content -->
    <div class="main-content">
        
        <!-- Origin Selection -->
        <div class="selection-card" onclick="selectStation('origin')">
            <div class="selection-icon">📍</div>
            <div class="selection-content">
                <div class="selection-label">fermata più vicina</div>
                <div class="selection-value" id="origin-value">Seleziona partenza</div>
            </div>
        </div>

        <!-- Swap Button -->
        <button class="swap-button" onclick="swapStations()">⇅</button>

        <!-- Destination Selection -->
        <div class="selection-card" onclick="selectStation('destination')">
            <div class="selection-icon">📍</div>
            <div class="selection-content">
                <div class="selection-label">selezionata prima</div>
                <div class="selection-value" id="destination-value">Seleziona destinazione</div>
            </div>
        </div>

        <!-- Date/Time Triggers -->
        <div class="datetime-section">
            <div class="section-label">seleziona data e ora partenza:</div>
            <div class="datetime-inputs">
                <div class="datetime-trigger" onclick="openDateModal()">
                    <span id="display-date"><?= date('d/m/Y') ?></span>
                    <span class="chevron">›</span>
                </div>
                <div class="datetime-trigger" onclick="openTimeModal()">
                    <span id="display-time"><?= date('H:i') ?></span>
                    <span class="chevron">›</span>
                </div>
            </div>
        </div>

        <!-- Return Trip Toggle -->
        <div class="toggle-container">
            <span class="toggle-label">ritorno</span>
            <label class="toggle-switch">
                <input type="checkbox" id="return-toggle" onchange="toggleReturn()">
                <span class="toggle-slider"></span>
            </label>
        </div>

        <!-- Search Button -->
        <button class="search-button" onclick="searchRoutes()">ricerca soluzioni</button>

    </div>

    <!-- Date Modal -->
    <div id="date-modal" class="modal-overlay">
        <div class="modal-content">
            <div class="modal-handle"></div>
            
            <!-- Simple Calendar Header -->
            <div class="calendar-header">
                <button onclick="changeMonth(-1)">‹</button>
                <span id="calendar-month-year">September 2025</span>
                <button onclick="changeMonth(1)">›</button>
            </div>
            
            <!-- Calendar Grid -->
            <div class="calendar-grid" id="calendar-grid">
                <!-- Days will be generated by JS -->
            </div>

            <div class="modal-actions">
                <button class="btn-primary" onclick="confirmDate()">fatto</button>
                <button class="btn-outline" onclick="closeDateModal()">annulla</button>
            </div>
        </div>
    </div>

    <!-- Time Modal -->
    <div id="time-modal" class="modal-overlay">
        <div class="modal-content">
            <div class="modal-handle"></div>
            
            <div class="time-picker-container">
                <div class="time-picker-wheel" id="hour-wheel">
                    <!-- Hours generated by JS -->
                </div>
                <div class="time-picker-separator">:</div>
                <div class="time-picker-wheel" id="minute-wheel">
                    <!-- Minutes generated by JS -->
                </div>
                <div class="time-picker-highlight"></div>
            </div>

            <div class="modal-actions">
                <button class="btn-primary" onclick="confirmTime()">fatto</button>
                <button class="btn-outline" onclick="closeTimeModal()">annulla</button>
            </div>
        </div>
    </div>

    <!-- Custom Pickers Styles moved to style.css -->

    <script>
        let selectedOrigin = null;
        let selectedDestination = null;
        
        // Date/Time State
        let currentDate = new Date();
        let selectedDate = new Date();
        let selectedHour = new Date().getHours();
        let selectedMinute = new Date().getMinutes();

        // --- Modal Logic ---
        function openDateModal() {
            document.getElementById('date-modal').style.display = 'flex';
            renderCalendar();
        }

        function closeDateModal() {
            document.getElementById('date-modal').style.display = 'none';
        }

        function confirmDate() {
            document.getElementById('display-date').textContent = formatDate(selectedDate);
            closeDateModal();
        }

        function openTimeModal() {
            document.getElementById('time-modal').style.display = 'flex';
            renderTimePicker();
        }

        function closeTimeModal() {
            document.getElementById('time-modal').style.display = 'none';
        }

        function confirmTime() {
            const h = selectedHour.toString().padStart(2, '0');
            const m = selectedMinute.toString().padStart(2, '0');
            document.getElementById('display-time').textContent = `${h}:${m}`;
            closeTimeModal();
        }

        // --- Calendar Logic ---
        function renderCalendar() {
            const grid = document.getElementById('calendar-grid');
            grid.innerHTML = '';
            
            const year = selectedDate.getFullYear();
            const month = selectedDate.getMonth();
            
            document.getElementById('calendar-month-year').textContent = selectedDate.toLocaleString('default', { month: 'long', year: 'numeric' });

            const firstDay = new Date(year, month, 1).getDay();
            const daysInMonth = new Date(year, month + 1, 0).getDate();

            // Empty slots
            for (let i = 0; i < firstDay; i++) {
                grid.appendChild(document.createElement('div'));
            }

            // Days
            for (let d = 1; d <= daysInMonth; d++) {
                const el = document.createElement('div');
                el.className = 'calendar-day';
                el.textContent = d;
                if (d === selectedDate.getDate()) el.classList.add('selected');
                
                el.onclick = () => {
                    selectedDate.setDate(d);
                    renderCalendar();
                };
                
                grid.appendChild(el);
            }
        }
        
        function changeMonth(delta) {
            selectedDate.setMonth(selectedDate.getMonth() + delta);
            renderCalendar();
        }

        // --- Time Picker Logic ---
        function renderTimePicker() {
            const hWheel = document.getElementById('hour-wheel');
            const mWheel = document.getElementById('minute-wheel');
            
            hWheel.innerHTML = '';
            mWheel.innerHTML = '';
            
            // Hours
            for (let i = 0; i < 24; i++) {
                const el = document.createElement('div');
                el.className = 'time-item';
                el.textContent = i.toString().padStart(2, '0');
                if (i === selectedHour) el.classList.add('active');
                
                el.onclick = () => {
                    selectedHour = i;
                    renderTimePicker(); // Re-render to update active class
                };

                hWheel.appendChild(el);
            }
            
            // Minutes
            for (let i = 0; i < 60; i+=5) { // 5 min steps for easier scrolling
                const el = document.createElement('div');
                el.className = 'time-item';
                el.textContent = i.toString().padStart(2, '0');
                if (i === selectedMinute) el.classList.add('active');
                
                el.onclick = () => {
                    selectedMinute = i;
                    renderTimePicker();
                };

                mWheel.appendChild(el);
            }
            
            // Scroll to selected
            setTimeout(() => {
                const itemHeight = 40; // Approx height
                hWheel.scrollTop = selectedHour * itemHeight - (hWheel.clientHeight / 2) + (itemHeight / 2);
                mWheel.scrollTop = (selectedMinute / 5) * itemHeight - (mWheel.clientHeight / 2) + (itemHeight / 2);
            }, 10);
            
            hWheel.onscroll = () => {
                // Calculate selected based on scroll position
                const index = Math.round(hWheel.scrollTop / 40);
                // selectedHour = index; // Don't auto-select on scroll, user clicks or we just use visual
                // Update styling
                Array.from(hWheel.children).forEach((c, i) => {
                    c.classList.toggle('active', i === index);
                });
            };
            
             mWheel.onscroll = () => {
                const index = Math.round(mWheel.scrollTop / 40);
                // selectedMinute = index * 5;
                 Array.from(mWheel.children).forEach((c, i) => {
                    c.classList.toggle('active', i === index);
                });
            };
        }

        // --- Pull to Cancel Logic ---
        function initPullToCancel(modalId, closeFunc) {
            const modal = document.getElementById(modalId);
            const content = modal.querySelector('.modal-content');
            const handle = modal.querySelector('.modal-handle');
            
            let startY = 0;
            let currentY = 0;
            let isDragging = false;
            
            const onTouchStart = (e) => {
                // Only trigger if touching the handle or top of content
                if (e.target === handle || e.target.closest('.modal-handle')) {
                    startY = e.touches[0].clientY;
                    isDragging = true;
                    content.style.transition = 'none';
                }
            };
            
            const onTouchMove = (e) => {
                if (!isDragging) return;
                currentY = e.touches[0].clientY;
                const diff = currentY - startY;
                
                if (diff > 0) {
                    e.preventDefault();
                    content.style.transform = `translateY(${diff}px)`;
                }
            };
            
            const onTouchEnd = (e) => {
                if (!isDragging) return;
                isDragging = false;
                const diff = currentY - startY;
                
                content.style.transition = 'transform 0.3s ease';
                
                if (diff > 100) { // Threshold to close
                    content.style.transform = 'translateY(100%)';
                    setTimeout(() => {
                        closeFunc();
                        content.style.transform = ''; // Reset
                    }, 300);
                } else {
                    content.style.transform = ''; // Bounce back
                }
            };
            
            handle.addEventListener('touchstart', onTouchStart, {passive: false});
            window.addEventListener('touchmove', onTouchMove, {passive: false});
            window.addEventListener('touchend', onTouchEnd);
        }

        // Initialize pull-to-cancel
        window.addEventListener('load', () => {
            initPullToCancel('date-modal', closeDateModal);
            initPullToCancel('time-modal', closeTimeModal);
        });

        function formatDate(date) {
            return date.toLocaleDateString('it-IT');
        }

        // --- Existing Logic ---
        function selectStation(type) {
            localStorage.setItem('route_selection_mode', type);
            window.location.href = '/station-selector?mode=select&type=' + type;
        }

        function swapStations() {
            const temp = selectedOrigin;
            selectedOrigin = selectedDestination;
            selectedDestination = temp;
            updateUI();
            saveState();
        }

        function updateUI() {
            document.getElementById('origin-value').textContent = selectedOrigin ? selectedOrigin.name : 'Seleziona partenza';
            document.getElementById('destination-value').textContent = selectedDestination ? selectedDestination.name : 'Seleziona destinazione';
        }

        function saveState() {
            if (selectedOrigin) localStorage.setItem('route_origin', JSON.stringify(selectedOrigin));
            else localStorage.removeItem('route_origin');
            
            if (selectedDestination) localStorage.setItem('route_destination', JSON.stringify(selectedDestination));
            else localStorage.removeItem('route_destination');
        }

        function searchRoutes() {
            if (!selectedOrigin || !selectedDestination) {
                alert('Seleziona sia la partenza che la destinazione');
                return;
            }

            const dateStr = selectedDate.toISOString().split('T')[0];
            const timeStr = `${selectedHour.toString().padStart(2, '0')}:${selectedMinute.toString().padStart(2, '0')}`;
            
            localStorage.setItem('route_departure_date', dateStr);
            localStorage.setItem('route_departure_time', timeStr);

            window.location.href = '/route-results';
        }

        function toggleReturn() {
            console.log("Toggle return not implemented yet");
            // dopo tot sec unchecka #return-toggle
            setTimeout(() => {
                document.getElementById('return-toggle').checked = false;
            }, 400);
        }

        window.addEventListener('DOMContentLoaded', () => {
            const savedOrigin = localStorage.getItem('route_origin');
            const savedDestination = localStorage.getItem('route_destination');

            if (savedOrigin) selectedOrigin = JSON.parse(savedOrigin);
            if (savedDestination) selectedDestination = JSON.parse(savedDestination);
            
            updateUI();
            
            // Initialize displays
            document.getElementById('display-date').textContent = formatDate(selectedDate);
            document.getElementById('display-time').textContent = `${selectedHour.toString().padStart(2, '0')}:${selectedMinute.toString().padStart(2, '0')}`;
        });
    </script>

</body>
</html>
