<!DOCTYPE html>
<html lang="it">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Trova Percorso - ACTV</title>
        <?php require COMMON_HTML_HEAD; ?>
        <link rel="stylesheet" href="/css/structure/structure-routeFinder.css">
        <link rel="stylesheet" href="/css/routeFinder.css">
        <script src="/js/routeFinder.js"></script>
    </head>
    <body>

        <!-- Header -->
        <div class="header-green">
            <div style="height: 20px;">
                <a href="/" style="color: white; text-decoration: none; font-size: 24px;">&larr;</a>
            </div>
            <div class="header-title">Trova<br>Percorso</div>
        </div>

        <!-- Main Content -->
        <div class="main-content">
            
            <!-- Origin Selection -->
            <div class="selection-card" onclick="selectStation('origin')">
                <div class="selection-icon">📍</div>
                <div class="selection-content">
                    <div class="selection-label">fermata più vicina</div>
                    <div class="selection-value" id="origin-value">Seleziona partenza</div>
                </div>
            </div>

            <!-- Swap Button -->
            <button class="swap-button" onclick="swapStations()">⇅</button>

            <!-- Destination Selection -->
            <div class="selection-card" onclick="selectStation('destination')">
                <div class="selection-icon">📍</div>
                <div class="selection-content">
                    <div class="selection-label">selezionata prima</div>
                    <div class="selection-value" id="destination-value">Seleziona destinazione</div>
                </div>
            </div>

            <!-- Date/Time Triggers -->
            <div class="datetime-section">
                <div class="section-label">seleziona data e ora partenza:</div>
                <div class="datetime-inputs">
                    <div class="datetime-trigger" onclick="openDateModal()">
                        <span id="display-date"><?= date('d/m/Y') ?></span>
                        <span class="chevron">›</span>
                    </div>
                    <div class="datetime-trigger" onclick="openTimeModal()">
                        <span id="display-time"><?= date('H:i') ?></span>
                        <span class="chevron">›</span>
                    </div>
                </div>
            </div>

            <!-- Return Trip Toggle -->
            <div class="toggle-container">
                <span class="toggle-label">ritorno</span>
                <label class="toggle-switch">
                    <input type="checkbox" id="return-toggle" onchange="toggleReturn()">
                    <span class="toggle-slider"></span>
                </label>
                <span style="font-size: 10px;">&nbsp;(non ancora implementato)</span>
            </div>

            <!-- Search Button -->
            <button class="search-button" onclick="searchRoutes()">ricerca soluzioni</button>

        </div>

        <!-- Date Modal -->
        <div id="date-modal" class="modal-overlay">
            <div class="modal-content">
                <div class="modal-handle"></div>
                
                <!-- Simple Calendar Header -->
                <div class="calendar-header">
                    <button class="btn" style="font-size: 24px;" onclick="changeMonth(-1)">‹</button>
                    <span id="calendar-month-year">September 2025</span>
                    <button class="btn" style="font-size: 24px;" onclick="changeMonth(1)">›</button>
                </div>
                
                <!-- Calendar Grid -->
                <div class="calendar-grid" id="calendar-grid">
                    <!-- Days will be generated by JS -->
                </div>

                <div class="modal-actions">
                    <button class="btn-primary" onclick="confirmDate()">fatto</button>
                    <button class="btn-outline" onclick="closeDateModal()">annulla</button>
                </div>
            </div>
        </div>

        <!-- Time Modal -->
        <div id="time-modal" class="modal-overlay">
            <div class="modal-content">
                <div class="modal-handle"></div>
                
                <div class="time-picker-container">
                    <div class="time-picker-wheel" id="hour-wheel">
                        <!-- Hours generated by JS -->
                    </div>
                    <div class="time-picker-separator">:</div>
                    <div class="time-picker-wheel" id="minute-wheel">
                        <!-- Minutes generated by JS -->
                    </div>
                    <div class="time-picker-highlight"></div>
                </div>

                <div class="modal-actions">
                    <button class="btn-primary" onclick="confirmTime()">fatto</button>
                    <button class="btn-outline" onclick="closeTimeModal()">annulla</button>
                </div>
            </div>
        </div>
    </body>
</html>
